---

- debug:
    msg: "is ARM: {{ansible_architecture}}"
  when: ansible_architecture == "aarch64"

- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: "{{cache_dir}}/{{ansible_architecture}}"
    state: directory
  delegate_to: localhost

- name: Has node been initialized?
  stat:
    path: "{{waydroid_images}}/{{images [0]}}"
  register: image_on_node

- name: Does proxy cache exist?
  stat:
    path: "{{cache_dir}}/{{ansible_architecture}}/{{images [0]}}"
  register: proxy_cache
  delegate_to: localhost

- name: Backup images from node to local
  ansible.builtin.fetch:
    src: "{{waydroid_images}}/{{item}}"
    dest: "{{cache_dir}}/{{ansible_architecture}}/"
    flat: yes
    validate_checksum: false
  loop: "{{images}}"
  when: (image_on_node.stat.exists and not proxy_cache.stat.exists) or (recreate_cache)
  # Will NOT work with Become! due to slurp
