---

# Can use either copy a Full file, or copy a template, and edit to add differences!

- name: Copy a premade kernel_config file
  ansible.builtin.copy:
    src: linux-rockchip64-edge.config
    dest: "{{userpatches}}/"
