---

# Todo: Has a tendency to ssh-timeout. https://www.axelerant.com/blog/how-handle-long-running-tasks-ansible
- name: Create archive of Waydroid init files
  community.general.archive:
    path:
    - "{{waydroid_dir}}/images"
    - "{{waydroid_dir}}/waydroid_base.prop"
    - "{{waydroid_dir}}/waydroid.cfg"
    dest: "/home/{{ansible_user}}/waydroid-init-{{ansible_architecture}}.tar.gz"
    format: gz
    owner: "{{ansible_user}}"
    group: "{{ansible_user}}"
  become: true