---

- name: Has node been initialized?
  stat:
    path: "{{waydroid_image_dir}}/{{images [0]}}"
  register: image_on_node

- name: Does proxy cache exist?
  stat:
    path: "{{cache_dir}}/{{ansible_architecture}}/images/{{images [0]}}"
  register: proxy_cache
  delegate_to: localhost
