---
- name: Create waydroid directory
  ansible.builtin.file:
    path: "{{waydroid_image_dir}}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  become: true

- name: Does proxy cache exist?
  stat:
    path: "{{cache_dir}}/{{ansible_architecture}}/{{images [0]}}"
  register: proxy_cache
  delegate_to: localhost

- debug:
    msg: "Proxy cache exists: {{proxy_cache.stat.exists}}"
  when: proxy_cache.stat.exists

- name: Restore image
  ansible.builtin.copy:
    src: "{{cache_dir}}/{{ansible_architecture}}/images/{{item}}"
    dest: "{{waydroid_image_dir}}/{{item}}"
    owner: root
    group: root
    mode: '0644'
    force: false
  loop: "{{images}}"
  become: true

- name: Restore waydroid init files
  ansible.builtin.fetch:
    src: "{{cache_dir}}/{{ansible_architecture}}/"
    dest: "{{waydroid_dir}}/{{item}}"
    flat: yes
    validate_checksum: false
  loop: "{{files}}"
  when: (image_on_node.stat.exists and not proxy_cache.stat.exists) or (recreate_cache)